Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,10 +55,10 @@ jobs:
 
       - name: Configure Databricks auth
         env:
-          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
-          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
+          DATABRICKS_HOST: ${{ secrets.DB_HOST }}
+          DATABRICKS_TOKEN: ${{ secrets.DB_TOKEN }}
         run: |
-          databricks configure --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN" --quiet
+          databricks configure --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN" #--quiet
 
       - name: Deploy the bundle
         run: |
@@ -86,12 +86,13 @@ jobs:
           JOB_NAME: "nyc_job"
         run: |
           echo "Running job: $JOB_NAME"
-          job_id=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="'"$JOB_NAME"'") | .job_id')
+          databricks bundle run $JOB_NAME
+          # job_id=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="'"$JOB_NAME"'") | .job_id')
           
-          if [ -z "$job_id" ]; then
-            echo "ERROR: Job not found. Check job name."
-            exit 1
-          fi
+          # if [ -z "$job_id" ]; then
+          #   echo "ERROR: Job not found. Check job name."
+          #   exit 1
+          # fi
           
-          run_id=$(databricks jobs run-now --job-id "$job_id" --output JSON | jq -r '.run_id')
-          echo "Triggered run ID: $run_id"
+          # run_id=$(databricks jobs run-now --job-id "$job_id" --output JSON | jq -r '.run_id')
+          echo "Triggered run job run: $JOB_NAME"
